// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(

      apiKey: "AIzaSyAoDcEWHD6rXaggFZsXgfyntP_TNIh0X6A",
      appId: "1:1006206635664:web:ecb749de4e9a7ff18b1215",
      messagingSenderId: "1006206635664",
      projectId: "wloskiegarnki",
      authDomain: "wloskiegarnki.firebaseapp.com",
      storageBucket: "wloskiegarnki.appspot.com",


  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyAoDcEWHD6rXaggFZsXgfyntP_TNIh0X6A",
    appId: "1:1006206635664:web:ecb749de4e9a7ff18b1215",
    messagingSenderId: "1006206635664",
    projectId: "wloskiegarnki",
    authDomain: "wloskiegarnki.firebaseapp.com",
    storageBucket: "wloskiegarnki.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyAoDcEWHD6rXaggFZsXgfyntP_TNIh0X6A",
    appId: "1:1006206635664:web:ecb749de4e9a7ff18b1215",
    messagingSenderId: "1006206635664",
    projectId: "wloskiegarnki",
    authDomain: "wloskiegarnki.firebaseapp.com",
    storageBucket: "wloskiegarnki.appspot.com",
    iosClientId: '1086627119682-cpa5vejcfs9voe3bp0ltf9kdstkc375u.apps.googleusercontent.com',
    iosBundleId: 'com.example.phoneAuthHandlerDemo',
  );
}
